'use client';
import { useState } from 'react';

const NOTES = [
  { n: 1,  title: `built for Iinn.`,                              note: `This is on screen when the call starts. Let Iinn see his name. Say nothing. Let the moment land. When he reacts, begin.` },
  { n: 2,  title: `this is not a traditional sales call.`,        note: `Say: "Bro, I want this call to be different from someone just pitching you." Pause. "You already told me the real problem — you've never committed to something in your life. You've always stopped. You said you don't have structure to follow." Pause. "So before I show you anything, I want to understand why that pattern keeps happening — and whether you're genuinely ready to build a different one." Then: "I'm going to ask questions, listen, and tell you exactly what I think. This is not about convincing you. It's about seeing whether this system actually fits you." Ask: "Fair?" Wait for him to agree.` },
  { n: 3,  title: `you've never committed to something.`,         note: `Let it sit. He said it himself. You're not judging him — you're naming it accurately. The moment he sees it framed as a structural problem rather than a character flaw, the entire conversation shifts. Don't add anything. Let him sit with it.` },
  { n: 4,  title: `your history.`,                                note: `These questions reveal the emotional pattern. Listen for what triggers the fall-off. Is it a missed day? A hard week at work? An obstacle? Use follow-ups freely: "tell me more." / "give me a real example." / "what does that cost you?" Do not judge anything. The goal is for him to understand his own pattern — not for you to tell him.` },
  { n: 5,  title: `what changed.`,                                note: `The last question is critical. He mentioned wanting to be present with friends and family. When he names the people in his life who would benefit — he's connecting this to something bigger than the gym. That's the emotional anchor. Once he names it, reflect it back: "so this is also about being the person they can count on." Let him confirm.` },
  { n: 6,  title: `where things stand today.`,                    note: `You are mapping the territory. Ask specifically about work — because if he wants to train at 5am, you need to know what his day looks like. The energy question often reveals sleep and food quality issues without asking directly. Ask for specifics. Numbers where possible. Let him lead.` },
  { n: 7,  title: `what you bring.`,                              note: `This section is not flattery. It is finding real evidence. He already demonstrated something: he scheduled this call at 6am Eastern and committed to training before it. When he says things like "I'm reliable at work when I care" — use that as proof that the consistency muscle exists. He just hasn't applied it to himself yet. Point that out: "you already know how to follow through. you've just never had a structure that held you accountable to yourself."` },
  { n: 8,  title: `five questions.`,                              note: `These are real commitment questions — not motivation questions. If he hesitates on any of them, explore it: "what makes that one harder than the others?" The last question is the most revealing. What he's willing to reorganize tells you how serious he actually is. Listen for specifics. A vague answer means he hasn't thought it through. Don't pressure. Just observe.` },
  { n: 9,  title: `what i'm actually hearing.`,                   note: `Read the observations one by one. Slowly. Leave space after each one. When you reach the script — pause before reading it. Read it deliberately. After the last line, pause for at least three seconds. Let him sit in it. He has probably never heard someone frame his own pattern this way without judgment. The silence is valuable — don't fill it.` },
  { n: 10, title: `you are not missing information.`,             note: `Simple. Clean. Let this be a clear beat between the diagnosis and the identity reframe. Ask: "Does that feel accurate?" He will say yes. That yes is important — it means he owns the diagnosis. From here, the program becomes the solution to his stated problem, not a product you're pitching.` },
  { n: 11, title: `your current identity is not permanent.`,      note: `Walk through both columns slowly. After the highlight line — stop. Let him read it. Ask: "Which column does the person you want to be live in?" He will point to the right. "Good. That's what the next eight weeks are for. Not proving you're perfect. Proving you don't disappear."` },
  { n: 12, title: `i already see something in you.`,             note: `This is not a sales technique. Say it with conviction — because you mean it. He has already demonstrated something by being on this call at this hour. Name that explicitly. Then shift: "But I'm not asking for motivation right now. I'm asking for a commitment to a standard." Pause. "There's a difference." Then advance to the portal.` },
  { n: 13, title: `everything lives in one place.`,               note: `Say: "Before I show you this — remote coaching doesn't mean less coaching. It means the right kind of coaching for your situation." Pause. "You said you want to be present with friends and family. More consistent at work. Training at 5am. None of that happens in the gym hour. It happens in the decisions you make the other 23 hours." Pause. "That's where I coach you." Open the portal at /portal/iinn-demo.` },
  { n: 14, title: `today's mission.`,                             note: `Show the Mission tab. Walk through each daily task. Point to the work block task and the presence task. Say: "One of the tasks is to complete one focused work block. That's in here intentionally — based on what you told me about work consistency." Show the check-in task. Say: "The evening check-in is what separates a good day from a building day. Two minutes. Every night." Ask: "Can you see yourself checking these off?"` },
  { n: 15, title: `one score. five pillars.`,                     note: `Say: "Most coaches only track workouts. I'm tracking the whole person." Point to the Presence pillar. "Presence is a tracked pillar — specifically around being there for your friends and family. That matters enough to have a score." Show a pillar expanded — walk through the score, what's helping, what's holding it back, and exactly what he needs to do to improve it. Ask: "Does it feel different to see all five areas tracked instead of just one?"` },
  { n: 16, title: `foundation of follow-through.`,                note: `Show the Fitness tab. Walk through Workout A. Read the program note out loud: "3 sessions per week. consistency over intensity. do not skip and do not add." Say: "The first two weeks are not about proving anything. They're about proving you can return." Ask: "Does this look manageable?" Then: "The goal is not to destroy you in week one. The goal is for you to still be here in week eight."` },
  { n: 17, title: `simple and repeatable.`,                       note: `Show the Nutrition tab. Walk through the daily checklist. Point to the grocery list. Say: "You will receive a weekly grocery list — you never have to think about what to buy. The decisions are already made." Then point to the protein target. "Protein at every meal is the one non-negotiable standard in week one. Everything else gets built on top of that." Ask: "Does simple and repeatable sound more useful than complicated and perfect?"` },
  { n: 18, title: `your week, structured.`,                       note: `Show the Schedule tab. Walk through the example weekly structure. Say: "I'm going to build your week around four anchors — gym, work, presence with the people you care about, and recovery. We'll confirm the exact days once you're enrolled and we do your intake." Ask: "Does seeing your week structured like this feel different from just having a workout plan?"` },
  { n: 19, title: `daily accountability.`,                        note: `Show the Check-In tab. Walk through the daily questions. Specifically point to: "were you present with the people around you?" and "where did you almost fall back into the old pattern?" Say: "That last question is the most important one I ask. I want to see where the pull toward the old behavior is happening — before it becomes abandonment." Ask: "Can you see yourself doing this every night — even on a hard day?"` },
  { n: 20, title: `what we track here is different.`,             note: `Show the Progress tab. Walk through the standard metrics. Then specifically point to RECOVERY WINS. Say: "Most apps track streaks. I track something different for you. A Recovery Win happens every time you miss or struggle — but return to the plan within 24 hours. That counts. Because your goal is not perfection. Your goal is ending the pattern of complete abandonment." Ask: "Can you see why that metric matters more for you than a perfect streak?"` },
  { n: 21, title: `this is what real coaching looks like.`,       note: `Show the Messages tab. Read the coach message out loud — slowly. "I do not care whether today was perfect. I care whether you disappear after today. Your old pattern was missing once and deciding the whole week was over. The new standard is simple: communicate, correct, and return. Tomorrow is another piece of evidence." Let it land. Ask: "Have you ever had a coach message like that before?"` },
  { n: 22, title: `the right fit.`,                               note: `Say: "I want to be honest about who this program is built for — and who it isn't." Let him read both columns. Then ask: "Based on what you know about yourself right now — where do you land?" Let him answer. That answer tells you everything. If he says he belongs in the left column — he's ready. If he hedges — explore that before moving forward.` },
  { n: 23, title: `everything built around your follow-through.`, note: `Walk through the list. Don't rush. Name the ones that stand out: "work-accountability structure" and "presence goals for friends and family." Say: "You'll notice some of these have nothing to do with the gym. That's intentional. You told me you wanted consistency in your work, with your friends, with your family. That's what this is built to support." Let the bottom line land.` },
  { n: 24, title: `8 weeks.`,                                     note: `Walk through each phase one at a time. After Weeks 1–2, ask: "Does this make sense? No proving anything. No intensity. Just evidence that you can return." After Weeks 3–4: "This is when you'll start to feel it — not because you're motivated, because you have data." After Weeks 5–6: "This is usually where programs fall apart. We're building you for this phase." After Weeks 7–8: "You'll have a record. Not a feeling. A record."` },
  { n: 25, title: `vveritas 8-week consistency rebuild.`,          note: `Walk through the feature list. Then say: "I want to be direct. I'm recommending remote not to give you less — but because the skill you need to build is disciplined execution without me in the room. You cannot build self-trust by having someone physically beside you every time you train. You build it by following through when no one is watching." Pause. "That is what the next eight weeks are for."` },
  { n: 26, title: `flexible payment options.`,                     note: `Say: "The investment stays the same regardless of how you structure it." Read the options calmly. "Pay in full, two payments, or four monthly." Then: "Your start date is locked in once the first payment is received." Ask: "Which schedule makes the most sense for where you are right now?" Don't suggest one. Let him choose. Don't apologize for the price.` },
  { n: 27, title: `based on everything you told me.`,             note: `Deliver this calmly. No urgency. No pressure. Read the recommendation slowly. After the prescription lines — pause. Then ask: "Does that match what you told me you need?" Don't pitch. Don't oversell. Let him confirm the recommendation is accurate.` },
  { n: 28, title: `this is what i recommend.`,                    note: `Deliver this with complete calm. No urgency. No fake scarcity. After the question — stop talking. Whatever he says next is the close. If he says yes: "Tell me exactly what you're committing to." Let him speak. Then: "Good. Based on that, I'm comfortable moving forward with you." Open /enroll/iinn. If he hesitates — move to objections.` },
  { n: 29, title: `whatever is holding you back.`,                note: `Do not bring this slide up unprompted. If he raises an objection, navigate here and click the matching one. These are frameworks — not scripts. Let the conversation lead.` },
  { n: 30, title: `your follow-through starts when you decide.`,  note: `Do not pitch. Do not oversell. Ask "what questions do you have before we move forward?" and go silent. Let him talk. Whatever he says next is your close. Open the enrollment page. Confirm his start date.` },
];

export default function IinnNotesPage() {
  const [active, setActive] = useState(0);
  const current = NOTES[active];

  return (
    <div style={{ background: '#000', minHeight: '100dvh', fontFamily: 'Inter, -apple-system, sans-serif', fontWeight: 300, color: '#EDEDE8', display: 'flex', flexDirection: 'column' }}>
      <div style={{ padding: '1.2rem 1.4rem 0.8rem', borderBottom: '1px solid #141414', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <span style={{ fontSize: '0.78rem', color: '#3A3A3A', letterSpacing: '0.02em' }}>vveritas* notes — iinn</span>
        <span style={{ fontFamily: 'ui-monospace, monospace', fontSize: '0.6rem', letterSpacing: '0.2em', color: '#3A3A3A' }}>{active + 1} / {NOTES.length}</span>
      </div>

      <div style={{ display: 'flex', gap: '4px', padding: '0.8rem 1.4rem', overflowX: 'auto', scrollbarWidth: 'none', borderBottom: '1px solid #0f0f0f' }}>
        {NOTES.map((_, i) => (
          <button key={i} onClick={() => setActive(i)} style={{ width: '20px', height: '20px', borderRadius: '2px', border: '1px solid', borderColor: i === active ? '#EDEDE8' : '#1a1a1a', background: i === active ? '#EDEDE8' : 'transparent', color: i === active ? '#000' : '#3A3A3A', fontFamily: 'ui-monospace, monospace', fontSize: '0.42rem', cursor: 'pointer', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            {i + 1}
          </button>
        ))}
      </div>

      <div style={{ flex: 1, padding: '1.5rem 1.4rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <div style={{ fontFamily: 'ui-monospace, monospace', fontSize: '0.52rem', letterSpacing: '0.3em', textTransform: 'uppercase', color: '#3A3A3A' }}>slide {current.n}</div>
        <div style={{ fontSize: '0.82rem', color: '#5A5A5A', letterSpacing: '-0.01em', lineHeight: 1.4 }}>"{current.title}"</div>
        <div style={{ fontSize: '1rem', lineHeight: 1.75, color: '#EDEDE8', flex: 1 }}>{current.note}</div>
      </div>

      <div style={{ padding: '1rem 1.4rem', borderTop: '1px solid #141414', background: '#000' }}>
        <div style={{ fontFamily: 'ui-monospace, monospace', fontSize: '0.5rem', letterSpacing: '0.3em', textTransform: 'uppercase', color: '#1a1a1a', marginBottom: '0.6rem', textAlign: 'center' }}>
          listen. diagnose. reflect. prescribe.
        </div>
        <div style={{ fontFamily: 'ui-monospace, monospace', fontSize: '0.44rem', letterSpacing: '0.1em', color: '#141414', textAlign: 'center' }}>
          he does not need more hype. he needs to hear his own reasons for changing.
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', borderTop: '1px solid #141414' }}>
        <button onClick={() => setActive(i => Math.max(i - 1, 0))} disabled={active === 0} style={{ padding: '1.1rem', background: 'none', border: 'none', borderRight: '1px solid #141414', color: active === 0 ? '#1a1a1a' : '#5A5A5A', fontFamily: 'inherit', fontSize: '0.85rem', cursor: active === 0 ? 'default' : 'pointer' }}>← prev</button>
        <button onClick={() => setActive(i => Math.min(i + 1, NOTES.length - 1))} disabled={active === NOTES.length - 1} style={{ padding: '1.1rem', background: 'none', border: 'none', color: active === NOTES.length - 1 ? '#1a1a1a' : '#EDEDE8', fontFamily: 'inherit', fontSize: '0.85rem', cursor: active === NOTES.length - 1 ? 'default' : 'pointer' }}>next →</button>
      </div>
    </div>
  );
}
