export const clients = [
  {
    id: 'c1',
    token: 'xK9mP2qLnR8v',
    name: 'alex thompson',
    tier: 'sovereign',
    price: 5000,
    status: 'active',
    startDate: '2026-05-01',
    blockStart: '2026-06-02',
    nextCheckIn: '2026-07-15',
    program: 'push pull legs — volume phase',
    lastWorkout: '2026-07-12',
    weeklyCheckIns: 3,
    momentum: 82,
    goal: 'body recomposition + trading discipline',
    weight: { current: 182, start: 195 },
    unread: 2,
  },
  {
    id: 'c2',
    token: 'tY4wJ7dFcM3b',
    name: 'marcus reid',
    tier: 'operator',
    price: 2750,
    status: 'active',
    startDate: '2026-06-01',
    blockStart: '2026-06-09',
    nextCheckIn: '2026-07-14',
    program: 'strength foundation — week 6',
    lastWorkout: '2026-07-11',
    weeklyCheckIns: 2,
    momentum: 64,
    goal: 'build muscle, lose fat',
    weight: { current: 210, start: 225 },
    unread: 0,
  },
  {
    id: 'c3',
    token: 'pQ6hN1sFgW5c',
    name: 'jordan silva',
    tier: 'foundation',
    price: 997,
    status: 'active',
    startDate: '2026-06-15',
    blockStart: '2026-06-23',
    nextCheckIn: '2026-07-16',
    program: 'hypertrophy block — month 1',
    lastWorkout: '2026-07-10',
    weeklyCheckIns: 1,
    momentum: 41,
    goal: 'first time lifting seriously',
    weight: { current: 165, start: 165 },
    unread: 1,
  },
  {
    id: 'c4',
    token: 'rB8xT3kYmZ2d',
    name: 'dante wells',
    tier: 'sovereign',
    price: 5000,
    status: 'stuck',
    startDate: '2026-04-01',
    blockStart: '2026-06-02',
    nextCheckIn: '2026-07-13',
    program: 'cut phase — deficit protocol',
    lastWorkout: '2026-07-08',
    weeklyCheckIns: 0,
    momentum: 18,
    goal: 'prep for summer, maintain strength',
    weight: { current: 178, start: 190 },
    unread: 0,
  },
];

export const programs = [
  {
    id: 'p1',
    name: 'push pull legs — volume phase',
    type: 'strength',
    weeks: 8,
    daysPerWeek: 6,
    assignedTo: ['c1'],
    workouts: [
      {
        id: 'w1',
        day: 'push',
        exercises: [
          { name: 'barbell bench press', sets: 4, reps: '6–8', rest: '3 min' },
          { name: 'incline dumbbell press', sets: 3, reps: '10–12', rest: '2 min' },
          { name: 'cable lateral raise', sets: 4, reps: '15–20', rest: '90 sec' },
          { name: 'overhead press', sets: 3, reps: '8–10', rest: '2 min' },
          { name: 'tricep pushdown', sets: 3, reps: '12–15', rest: '90 sec' },
          { name: 'overhead tricep extension', sets: 3, reps: '12–15', rest: '90 sec' },
        ],
      },
      {
        id: 'w2',
        day: 'pull',
        exercises: [
          { name: 'pull-ups', sets: 4, reps: 'max', rest: '3 min' },
          { name: 'barbell row', sets: 4, reps: '6–8', rest: '3 min' },
          { name: 'cable row', sets: 3, reps: '10–12', rest: '2 min' },
          { name: 'face pull', sets: 4, reps: '15–20', rest: '90 sec' },
          { name: 'barbell curl', sets: 3, reps: '10–12', rest: '90 sec' },
          { name: 'hammer curl', sets: 3, reps: '12–15', rest: '90 sec' },
        ],
      },
      {
        id: 'w3',
        day: 'legs',
        exercises: [
          { name: 'barbell squat', sets: 4, reps: '6–8', rest: '3 min' },
          { name: 'romanian deadlift', sets: 3, reps: '10–12', rest: '2 min' },
          { name: 'leg press', sets: 3, reps: '12–15', rest: '2 min' },
          { name: 'leg curl', sets: 4, reps: '10–12', rest: '90 sec' },
          { name: 'calf raise', sets: 4, reps: '15–20', rest: '60 sec' },
        ],
      },
    ],
  },
  {
    id: 'p2',
    name: 'strength foundation — week 6',
    type: 'strength',
    weeks: 12,
    daysPerWeek: 4,
    assignedTo: ['c2'],
    workouts: [
      {
        id: 'w4',
        day: 'upper a',
        exercises: [
          { name: 'bench press', sets: 5, reps: '5', rest: '3 min' },
          { name: 'pendlay row', sets: 5, reps: '5', rest: '3 min' },
          { name: 'overhead press', sets: 3, reps: '8', rest: '2 min' },
          { name: 'pull-ups', sets: 3, reps: '8', rest: '2 min' },
        ],
      },
      {
        id: 'w5',
        day: 'lower a',
        exercises: [
          { name: 'squat', sets: 5, reps: '5', rest: '3 min' },
          { name: 'deadlift', sets: 3, reps: '5', rest: '4 min' },
          { name: 'leg press', sets: 3, reps: '10', rest: '2 min' },
        ],
      },
    ],
  },
  {
    id: 'p3',
    name: 'hypertrophy block — month 1',
    type: 'hypertrophy',
    weeks: 4,
    daysPerWeek: 4,
    assignedTo: ['c3'],
    workouts: [],
  },
  {
    id: 'p4',
    name: 'cut phase — deficit protocol',
    type: 'fat loss',
    weeks: 6,
    daysPerWeek: 5,
    assignedTo: ['c4'],
    workouts: [],
  },
];

export const messages = [
  {
    id: 'm1',
    clientId: 'c1',
    thread: [
      { from: 'client', text: 'finished today\'s push session. bench went up 5lbs. felt strong.', time: '2026-07-12 09:14' },
      { from: 'coach', text: 'that\'s what i want to see. keep the form tight on the incline. video next session.', time: '2026-07-12 10:30' },
      { from: 'client', text: 'will do. nutrition has been clean this week too', time: '2026-07-12 11:02' },
      { from: 'client', text: 'also wanted to ask about adding more cardio. thoughts?', time: '2026-07-13 08:45' },
    ],
  },
  {
    id: 'm2',
    clientId: 'c2',
    thread: [
      { from: 'coach', text: 'how did the lower body session go yesterday?', time: '2026-07-11 14:00' },
      { from: 'client', text: 'squats felt heavy but i got all 5 sets. deadlift was solid.', time: '2026-07-11 17:30' },
    ],
  },
  {
    id: 'm3',
    clientId: 'c3',
    thread: [
      { from: 'client', text: 'hey nico, quick question on the meal plan — can i swap rice for potatoes?', time: '2026-07-13 07:20' },
    ],
  },
  {
    id: 'm4',
    clientId: 'c4',
    thread: [
      { from: 'coach', text: 'dante, haven\'t seen a check-in this week. what\'s going on?', time: '2026-07-11 10:00' },
    ],
  },
];

export const groceryLists = [
  {
    clientId: 'c1',
    week: '2026-07-14',
    note: 'high protein recomp. heavy beef, eggs, raw dairy. fruit for carbs around training.',
    items: [
      { category: 'protein', name: 'grass-fed ground beef (80/20)', qty: '3 lbs' },
      { category: 'protein', name: 'pasture-raised eggs', qty: '2 dozen' },
      { category: 'protein', name: 'wild-caught salmon', qty: '1.5 lbs' },
      { category: 'protein', name: 'grass-fed bison', qty: '1 lb' },
      { category: 'protein', name: 'beef liver', qty: '½ lb' },
      { category: 'dairy', name: 'raw whole milk', qty: '½ gallon' },
      { category: 'dairy', name: 'grass-fed butter', qty: '1 block' },
      { category: 'dairy', name: 'raw cheddar cheese', qty: '½ lb' },
      { category: 'fat', name: 'ghee', qty: '1 jar' },
      { category: 'fat', name: 'coconut oil', qty: '1 jar' },
      { category: 'carbs', name: 'sweet potato', qty: '4 medium' },
      { category: 'carbs', name: 'bananas', qty: '6' },
      { category: 'carbs', name: 'blueberries', qty: '2 pints' },
      { category: 'carbs', name: 'mango', qty: '3' },
      { category: 'carbs', name: 'raw honey', qty: '1 jar' },
      { category: 'other', name: 'sea salt', qty: 'as needed' },
      { category: 'other', name: 'mineral water', qty: '1 case' },
    ],
  },
  {
    clientId: 'c2',
    week: '2026-07-14',
    note: 'strength phase. caloric deficit starting next week — keep beef and eggs high, pull back on dairy.',
    items: [
      { category: 'protein', name: 'grass-fed ground beef (80/20)', qty: '2.5 lbs' },
      { category: 'protein', name: 'pasture-raised eggs', qty: '18 eggs' },
      { category: 'protein', name: 'wild-caught sardines', qty: '4 cans' },
      { category: 'protein', name: 'grass-fed ribeye', qty: '1 lb' },
      { category: 'dairy', name: 'raw whole milk', qty: '1 quart' },
      { category: 'dairy', name: 'grass-fed butter', qty: '1 block' },
      { category: 'fat', name: 'tallow', qty: '1 jar' },
      { category: 'fat', name: 'coconut oil', qty: '1 jar' },
      { category: 'carbs', name: 'sweet potato', qty: '3 medium' },
      { category: 'carbs', name: 'bananas', qty: '5' },
      { category: 'carbs', name: 'strawberries', qty: '1 lb' },
      { category: 'carbs', name: 'raw honey', qty: '1 jar' },
      { category: 'other', name: 'sea salt', qty: 'as needed' },
    ],
  },
];

export const payments = [
  { id: 'pay1', clientId: 'c1', amount: 5000, status: 'paid', date: '2026-05-01', method: 'stripe', tier: 'sovereign' },
  { id: 'pay2', clientId: 'c2', amount: 2750, status: 'paid', date: '2026-06-09', method: 'stripe', tier: 'operator' },
  { id: 'pay3', clientId: 'c3', amount: 997, status: 'paid', date: '2026-06-23', method: 'stripe', tier: 'foundation' },
  { id: 'pay4', clientId: 'c4', amount: 5000, status: 'paid', date: '2026-06-02', method: 'stripe', tier: 'sovereign' },
];

export const nutrition = [
  {
    clientId: 'c1',
    targets: { calories: 2800, protein: 210, carbs: 320, fat: 80 },
    log: [
      { date: '2026-07-12', calories: 2750, protein: 205, carbs: 310, fat: 78 },
      { date: '2026-07-11', calories: 2900, protein: 215, carbs: 335, fat: 82 },
      { date: '2026-07-10', calories: 2650, protein: 198, carbs: 295, fat: 76 },
    ],
  },
  {
    clientId: 'c2',
    targets: { calories: 2400, protein: 180, carbs: 260, fat: 75 },
    log: [
      { date: '2026-07-12', calories: 2350, protein: 175, carbs: 250, fat: 72 },
      { date: '2026-07-11', calories: 2500, protein: 185, carbs: 275, fat: 78 },
    ],
  },
];
