'use client';
import { useState } from 'react';

const NOTES = [
  { n: 1, title: 'built for Ron Blake.', note: "Open with this on screen before the call starts. Let Ron see his name. That alone tells him this isn't a generic pitch — it was made for him. Don't say anything until he reacts." },
  { n: 2, title: 'this is not a traditional sales call.', note: "Say slowly: \"Before I walk you through what I built, I want to set the expectation for this conversation. This isn't a traditional sales call where I try to convince you to buy something. I want to understand where you are, what's stopped you before, and whether I genuinely believe my system is the right fit for you.\" Pause. \"You should be deciding whether you trust me to coach you — and I'm also deciding whether I believe you're ready to uphold the standards of the program. If I don't think it fits, I'll tell you directly.\" Then ask: \"Fair?\" Wait for him to agree." },
  { n: 3, title: 'the standard.', note: "Let him read this. Then say: \"Perfection isn't required. Participation is. A missed workout doesn't disqualify you. Disappearing, avoiding communication, and refusing feedback — those are what make coaching ineffective.\" Now move to your phone and ask the diagnostic questions. Listen for evidence, not promises. Ask for examples. Do not reward answers that just sound motivated." },
  { n: 4, title: 'what this relationship looks like.', note: "Say: \"Before I show you what I've built, I want to be clear about what this relationship looks like from both sides.\" Read the left column. Then: \"And here's what I'd need from you.\" Read the right. Then: \"I don't expect perfection. I expect communication and effort. If you give me those things, I can coach you.\" Ask: \"Does that feel like something you can genuinely commit to?\" Wait. Don't fill the silence." },
  { n: 5, title: "most people don't fail because they don't try.", note: "Pause here. Let that land. This is Ron's reality — he's tried before. He knows this feeling. You're naming it without making him feel judged." },
  { n: 6, title: 'this is not a workout plan.', note: 'The shift from "workout plan" to "operating system" is the key reframe. You\'re not selling sessions. You\'re selling a system that runs his health.' },
  { n: 7, title: 'what you told me.', note: 'Read these back to him slowly. Every person wants to feel heard. This moment — seeing his own words on the screen — is what makes this feel personal. Let him say "yes, that\'s me."' },
  { n: 8, title: 'everything lives in one place.', note: "Don't open the portal yet. Say: \"Before I show you this, I want to be straight about something.\" Then advance to the next slide." },
  { n: 9, title: "the hour we spend together isn't what determines your results.", note: "Say slowly: \"You reached out because you wanted a personal trainer. And you might be thinking — this is way more than I asked for. And honestly? You're right.\" Pause. \"The hour we spend together isn't what determines your results. Your results come from the other 167 hours of the week. So I built a system that coaches you there too.\" Now open the portal." },
  { n: 10, title: "today's mission.", note: 'Show the mission tab. Click through the tasks. Point out the streak counter and the self-mastery score. Say: "This is what I would expect you to complete each day. Can you see yourself doing this?" Let him interact mentally with it.' },
  { n: 11, title: 'one number. five pillars.', note: 'Most trainers only track workouts. You\'re tracking the whole person. Say: "This is where I would know whether you\'re following through — not just in the gym, but across all five pillars. Your score right now is 62. Over the next 12 weeks, we move this number together."' },
  { n: 12, title: 'foundation phase.', note: 'Show the fitness tab. Walk through Workout A. Read a coaching note out loud — "control the lowering phase — 2 seconds down." Say: "This is what I would review as your coach. I\'m paying attention to HOW you train, not just what you do."' },
  { n: 13, title: 'quality over volume.', note: "This is how you differentiate yourself from every trainer who just destroyed someone in session one. Say: \"I'm not going to impress you with volume. I'm going to build you a foundation that actually holds.\"" },
  { n: 14, title: "today's standards.", note: "Show the nutrition tab. Point out the progress numbers (130/150g protein, 2/3 meals, 70/90oz water). Say: \"This is where I would know whether you're eating or not — before you even message me. This week we're not chasing perfect. We're building the habit of showing up.\"" },
  { n: 15, title: 'your list. every week.', note: "This one always gets a reaction. People don't expect the grocery list. Say: \"You never have to think about what to buy. I've already decided. And if you follow this, you don't need to count a single calorie.\"" },
  { n: 16, title: '221 lbs. goal: 195.', note: 'Show the progress tab. Point to the weight goal bar. Say: "This is how we catch a bad week before it becomes a bad month. Every number is tracked. Nothing hides." Show the photo placeholders — say: "Week 1 we take your baseline. Week 12 we compare. The transformation is yours."' },
  { n: 17, title: 'daily accountability.', note: "Show the check-in tab. Walk through the questions. Say: \"This is how I stay ahead of problems. I'm not waiting for you to tell me something is off — I can see it here before you even think to reach out.\"" },
  { n: 18, title: 'this is what real coaching looks like.', note: "This is the moment. Read the final message out loud — slowly. Let him feel what it would be like to receive that. Most people have never had a coach who checks in like this. Then say: \"This is what attention between sessions looks like.\" Let it land." },
  { n: 19, title: 'wednesday. 6:00 pm.', note: "Say: \"I build the entire system around your schedule — not the other way around. The in-person session is the anchor. Everything else runs around it.\"" },
  { n: 20, title: 'the right fit.', note: "Say: \"I want to be honest about who this is built for — and who it isn't.\" Let him read both columns. Then: \"This isn't about being perfect. It's about being honest, coachable, and willing to keep showing up.\" Ask: \"Based on what you know about yourself — where do you land on this list?\" Let him answer. That answer tells you everything." },
  { n: 21, title: "let me tell you what i honestly think.", note: "Say with conviction: \"Before I show you the options, I want to be straight with you. I'm not going to ask you to pick from a menu. My job is to recommend the level of support I believe matches your goals, experience, and current level of accountability.\" Then: \"Based on what you've told me, I believe you are coachable and that this can work — but only if you're willing to uphold the standards we just discussed.\" Then advance to Elite first so he sees the full range." },
  { n: 22, title: 'elite transformation — maximum hands-on coaching.', note: "Show Elite first so he sees the full scope. Walk through the features. Let the price land. Then say: \"This is the highest level. Three sessions a week with me. If you need maximum hands-on support, this is it.\" Then advance to Hybrid." },
  { n: 23, title: 'hybrid coaching — the ideal balance.', note: "Say: \"This is the one I'd actually recommend for you.\" Pause. \"One session a week is enough to correct your form, push your performance, and hold you accountable. The system runs every other day — you're not on your own between sessions.\" Then: \"I'm not recommending this because it's cheaper. I'm recommending it because I don't think you need three sessions a week to get the result you described.\" Let that land." },
  { n: 24, title: 'remote coaching — complete coaching, full flexibility.', note: "Present as a continuation option, not a downgrade. Say: \"If your schedule ever changes — you travel, you move — you don't lose the coaching. Same system, same accountability, just done virtually. The quality doesn't change. The access does.\"" },
  { n: 25, title: 'every level. same system.', note: "Let him scan the whole table. Then point to the in-person coaching row: \"That's the only real difference. Everything else — the program, the nutrition, the dashboard, the messaging — you get all of that regardless of which level you choose.\"" },
  { n: 26, title: 'hybrid coaching. 8 weeks. (my recommendation)', note: "Read the reasons out loud — slowly. Then say: \"And here's what I don't think you need right now.\" Read those too. Then: \"My recommendation is conditional on three things: you attend the weekly in-person session, you complete the two independent workouts, and you communicate honestly through the portal. If you're not willing to do those three things, I'd rather not enroll you — because I don't want to take your money for a program you're not positioned to use.\"" },
  { n: 27, title: '8 weeks.', note: "Don't promise specific results. Explain the logic. Four weeks is a sprint. Eight weeks is where real consistency sets in. Twelve is for someone who wants to do it right the first time. Say: \"That's the timeline I'd recommend for you.\"" },
  { n: 28, title: 'flexible payment options.', note: "Say naturally: \"I want to make this as easy as possible. We can structure the payment however works best for you — pay in full, split into two, or monthly installments. The total stays the same either way.\"" },
  { n: 29, title: 'choose your coaching experience.', note: "Say: \"Based on everything you told me, I'd recommend the 8-week Hybrid. The investment is $2,300 — and we can structure the payment however works for you.\" Pause. \"The question I need you to answer is whether you're genuinely ready to uphold the standard we discussed.\" Pause. \"Do you believe you're ready for that?\" Let him answer. If yes: \"What specifically are you committing to?\" Let him say it out loud. Then: \"Good. Based on what you've told me, I'm comfortable moving forward.\"" },
  { n: 30, title: 'the only thing left is the decision.', note: "Do not pitch. Do not fill silence. Ron talks next. Whatever he says is your close. If he asks about price — you're ready. If he has objections — address them. If he says \"let's do it\" — great. If he needs time: \"Totally fair. What's the one thing you'd want to think through?\" Surface it. Never invent urgency." },
];

export default function NotesPage() {
  const [active, setActive] = useState(0);
  const current = NOTES[active];

  return (
    <div style={{ background: '#000', minHeight: '100dvh', fontFamily: 'Inter, -apple-system, sans-serif', fontWeight: 300, color: '#EDEDE8', display: 'flex', flexDirection: 'column' }}>
      <div style={{ padding: '1.2rem 1.4rem 0.8rem', borderBottom: '1px solid #141414', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <span style={{ fontSize: '0.78rem', color: '#3A3A3A', letterSpacing: '0.02em' }}>vveritas* notes</span>
        <span style={{ fontFamily: 'ui-monospace, monospace', fontSize: '0.6rem', letterSpacing: '0.2em', color: '#3A3A3A' }}>{active + 1} / {NOTES.length}</span>
      </div>
      <div style={{ display: 'flex', gap: '4px', padding: '0.8rem 1.4rem', overflowX: 'auto', scrollbarWidth: 'none', borderBottom: '1px solid #0f0f0f' }}>
        {NOTES.map((_, i) => (
          <button key={i} onClick={() => setActive(i)} style={{ width: '20px', height: '20px', borderRadius: '2px', border: '1px solid', borderColor: i === active ? '#EDEDE8' : '#1a1a1a', background: i === active ? '#EDEDE8' : 'transparent', color: i === active ? '#000' : '#3A3A3A', fontFamily: 'ui-monospace, monospace', fontSize: '0.42rem', cursor: 'pointer', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            {i + 1}
          </button>
        ))}
      </div>
      <div style={{ flex: 1, padding: '1.5rem 1.4rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <div style={{ fontFamily: 'ui-monospace, monospace', fontSize: '0.52rem', letterSpacing: '0.3em', textTransform: 'uppercase', color: '#3A3A3A' }}>slide {current.n}</div>
        <div style={{ fontSize: '0.82rem', color: '#5A5A5A', letterSpacing: '-0.01em', lineHeight: 1.4 }}>"{current.title}"</div>
        <div style={{ fontSize: '1rem', lineHeight: 1.75, color: '#EDEDE8', flex: 1 }}>{current.note}</div>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', borderTop: '1px solid #141414' }}>
        <button onClick={() => setActive(i => Math.max(i - 1, 0))} disabled={active === 0} style={{ padding: '1.1rem', background: 'none', border: 'none', borderRight: '1px solid #141414', color: active === 0 ? '#1a1a1a' : '#5A5A5A', fontFamily: 'inherit', fontSize: '0.85rem', cursor: active === 0 ? 'default' : 'pointer' }}>← prev</button>
        <button onClick={() => setActive(i => Math.min(i + 1, NOTES.length - 1))} disabled={active === NOTES.length - 1} style={{ padding: '1.1rem', background: 'none', border: 'none', color: active === NOTES.length - 1 ? '#1a1a1a' : '#EDEDE8', fontFamily: 'inherit', fontSize: '0.85rem', cursor: active === NOTES.length - 1 ? 'default' : 'pointer' }}>next →</button>
      </div>
    </div>
  );
}
